# Generated by Django 3.1.4 on 2020-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesBDs', '0004_auto_20201227_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='commentaire',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
