# Generated by Django 3.1.4 on 2020-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesBDs', '0006_auto_20201227_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="date d'achat"),
        ),
    ]
